model: "gpt-3.5-turbo" # gpt-4o, gpt-3.5-turbo
embedding: "openai"
retriever: "dense" # dense, sparse, hybrid
text_splitter: "character" # sentence, character, semantic, recursive
prompt: "history_aware" # history_aware, contextualize_q, qa_assistant
chunk_size: 1000
chunk_overlap: 200
query_translation: "multi_query" # multi_query, rag_fusion, decomposition, hyde