model: "gpt-4o" # gpt-4o, gpt-3.5-turbo, gpt-4-turbo
embedding: "openai"
retriever: "dense" # dense, sparse, hybrid
text_splitter: "semantic" # sentence, character, semantic, recursive
prompt: "history_aware" # history_aware, contextualize_q, qa_assistant
chunk_size: 300 # chunk_size
chunk_overlap: 50 # chunk_overlap
query_translation: "hyde" # multi_query, rag_fusion, decomposition, hyde